-- MySQL Script generated by MySQL Workbench
-- 09/30/21 17:03:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes` DEFAULT CHARACTER SET latin1 ;
USE `notes` ;

-- -----------------------------------------------------
-- Table `notes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `notes`.`notes_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`notes_text` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `creation` DATE NOT NULL,
  `modification` DATE NOT NULL,
  `elimination` TINYINT(4) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notes_text_category_note_idx` (`category_id` ASC),
  INDEX `fk_notes_text_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_notes_text_category_note`
    FOREIGN KEY (`category_id`)
    REFERENCES `notes`.`categories_notes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notes_text_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `notes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `notes`.`categories_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`categories_notes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `notes_text_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_notes_note_text_idx` (`notes_text_id` ASC),
  CONSTRAINT `fk_categories_notes_note_text`
    FOREIGN KEY (`notes_text_id`)
    REFERENCES `notes`.`notes_text` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
